// @vitest-environment jsdom
import { act, cleanup, renderHook, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { authenticatedFetch } from '../../../utils/api';
import { useApproverSession } from './useApproverSession';
import { createPublicApprovalClient } from './public-approval-client';
vi.mock('../../../utils/api', () => ({ authenticatedFetch: vi.fn() }));
const request = vi.mocked(authenticatedFetch);
const options = (index: number) => request.mock.calls[index][1] as RequestInit;
const user = { id: 'sd-user', username: 'approver', tenant_id: 'tenant' };
beforeEach(() => { vi.resetAllMocks(); localStorage.clear(); sessionStorage.clear(); });
afterEach(cleanup);
it('uses normal login and supplies the independent bearer to the actual approval client, memory only', async () => {
  request.mockResolvedValueOnce(new Response(JSON.stringify({ token: 'normal-sd-login', user })));
  const { result } = renderHook(() => useApproverSession('pd-owner'));
  await act(async () => { await result.current.login('approver', 'synthetic-password'); });
  expect(result.current.user).toEqual(user);
  expect(result.current.readApproverBearer()).toBe('normal-sd-login');
  expect(JSON.parse(String(options(0).body))).toEqual({ username: 'approver', password: 'synthetic-password' });
  request.mockResolvedValueOnce(new Response(JSON.stringify({ status: { sessionId: 'session', revision: 1, state: {} } })));
  await createPublicApprovalClient(result.current.readApproverBearer).status({ sessionKey: 'session' });
  expect(options(1).headers).toEqual({ 'X-StaffDeck-Approver-Authorization': 'Bearer normal-sd-login' });
  expect(localStorage.length + sessionStorage.length).toBe(0);
  const before = result.current.revision;
  act(() => result.current.logout());
  expect(result.current.readApproverBearer()).toBe('');
  expect(result.current.revision).toBeGreaterThan(before);
});
it.each([[401, 'APPROVAL_AUTH_REQUIRED'], [403, 'APPROVAL_SUBJECT_MISMATCH'], [403, 'USER_DISABLED']])('keeps %s rejection visible and no approver bearer', async (status, code) => {
  request.mockResolvedValueOnce(new Response(JSON.stringify({ code }), { status }));
  const { result } = renderHook(() => useApproverSession('pd-owner'));
  await act(async () => { await result.current.login('approver', 'synthetic-password'); });
  expect(result.current.error).toBe(code);
  expect(result.current.readApproverBearer()).toBe('');
});
it('revalidates on focus and removes an expired session', async () => {
  request.mockResolvedValueOnce(new Response(JSON.stringify({ token: 'normal-sd-login', user })));
  const { result } = renderHook(() => useApproverSession('pd-owner'));
  await act(async () => { await result.current.login('approver', 'synthetic-password'); });
  request.mockResolvedValueOnce(new Response(JSON.stringify({ code: 'APPROVAL_AUTH_REQUIRED' }), { status: 401 }));
  act(() => window.dispatchEvent(new Event('focus')));
  await waitFor(() => expect(result.current.user).toBeNull());
  expect(request.mock.calls[1][0]).toBe('/api/sop/approver/session');
  expect(result.current.readApproverBearer()).toBe('');
});
it('aborts pending login on logout, owner change and unmount, ignores late responses', async () => {
  let finish!: (value: Response) => void;
  request.mockImplementationOnce(() => new Promise(resolve => { finish = resolve; }));
  const { result, rerender, unmount } = renderHook(({ id }) => useApproverSession(id), { initialProps: { id: 'owner-a' } });
  let operation!: Promise<void>;
  act(() => { operation = result.current.login('approver', 'synthetic-password'); });
  const signal = options(0).signal;
  rerender({ id: 'owner-b' });
  expect(signal?.aborted).toBe(true);
  await act(async () => { finish(new Response(JSON.stringify({ token: 'late-token', user }))); await operation; });
  expect(result.current.readApproverBearer()).toBe('');
  request.mockImplementationOnce(() => new Promise(resolve => { finish = resolve; }));
  act(() => { operation = result.current.login('approver', 'synthetic-password'); });
  act(() => result.current.logout());
  expect(options(1).signal?.aborted).toBe(true);
  await act(async () => { finish(new Response(JSON.stringify({ token: 'late-token', user }))); await operation; });
  request.mockImplementationOnce(() => new Promise(resolve => { finish = resolve; }));
  act(() => { operation = result.current.login('approver', 'synthetic-password'); });
  const lastSignal = options(2).signal;
  unmount();
  expect(lastSignal?.aborted).toBe(true);
  finish(new Response(JSON.stringify({ token: 'late-token', user })));
  await operation;
  expect(result.current.readApproverBearer()).toBe('');
});
